# Generated by Django 5.0.1 on 2024-04-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
